service: rest-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  timeout: 300
  apiKeys:
    - todoAPI

package:
  include:
    - features/**
    - models/**
    - include-me-dir/**

functions:
  getTodo:
    handler: features/read.getTodo
    events:
      - http:
          path: todo/{id}
          method: get
          private: true

  listTodos:
    handler: features/read.listTodos
    events:
      - http:
          path: todos
          method: get

  createTodo:
    handler: features/create.createTodo
    events:
      - http:
          path: todo
          method: post
          private: true

  deleteTodo:
    handler: features/delete.deleteTodo
    events:
      - http:
          path: todo/{id}
          method: delete
          private: true

  updateTodo:
    handler: features/update.updateTodo
    events:
      - http:
          path: todo/{id}
          method: patch
          private: true
